New structure and hero component fix.
KodifyDevs/newwebsite.ui pull request #12
Opened 2024-05-13 01:31 UTC by Jmorales1306

## Description
- New structure and hero component fix.

## Pull request checklist
Please check if your PR fulfills the following requirements:
- [X] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed. (Add screenshot)
- [ ] Is my code avoiding performance problems (ex: rendering issues, amount of queries against the database, n+1 problem, infinite loops, memory usage)
- [ ] Is my code handling integration exceptions (ex: timeout error while calling an external service)
- [ ] My code includes usage metrics (ex: google analytics events, logs)
- [ ] My code includes restriction of access based on roles and permissions

## Pull request type
 
 

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## JIRA Ticket Link

JIRA Ticket:
WEB-25
![Hero_4k](https://github.com/KodifyDevs/newwebsite.ui/assets/48782219/362e14fd-22b4-4b50-9157-ad00617bb014)
![Hero_laptop](https://github.com/KodifyDevs/newwebsite.ui/assets/48782219/c97c6441-ec2a-45d7-8240-9db5a02014ae)
![Hero_Air](https://github.com/KodifyDevs/newwebsite.ui/assets/48782219/ba2e0857-8525-46d3-977a-7c5ed68e53ce)
![Hero_tablet](https://github.com/KodifyDevs/newwebsite.ui/assets/48782219/b8020f71-5974-4d8b-bacd-a6d4a47cb260)
![Hero_mobile](https://github.com/KodifyDevs/newwebsite.ui/assets/48782219/1e11c182-b4a0-4b0a-b41b-40e7980a4313)

## Commands to be executed or config files to be changed
- 

## Other information / Screenshots (Required for UI Changes)

2024-05-13 15:51 UTC, HamiltonG98 requested changes

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/app/layout.tsx
> +          <Hero />
El Hero no es parte del layout, ya que es parte del main page

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +          <div className="w-full bg-[#8B8C891A]">
Los colores deberian estar registrados en las variables de tailwind

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +            <div className="max-w-[1553px] lg:h-[580px] xl:h-[580px] 2xl:h-[580px] xl:flex 2xl:flex xl:mx-auto 2xl:mx-auto">
Si en lg ya tenes definido el height de 580px no es necesario que lo definas en xl y 2xl, ya que va en orden ascendente, entonces a menos que vos le indiques otro cambio, no deberia cambiar

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +              <div className="w-fit mx-auto xl:mt-[140px] 2xl:mt-[140px]">
Aqui lo mismo

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +                <div className="px-4 pt-6 text-left xl:w-[537px] 2xl:w-[537px]">
Aqui lo mismo

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +                  <h1 className="title font-bold text-richBlack leading-leading-title xl:leading-leading-title-desk 2xl:leading-leading-title-desk">
Lo mismo con las demas propiedades

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +                  <h2 className="mt-4 font-semibold text-2xl leading-leading-7 md:text-3xl lg:text-3xl xl:text-3xl 2xl:text-3xl md:leading-10 lg:leading-10 xl:leading-10 2xl:leading-10 text-richBlack
Y aqui tambien

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +                    <p className="font-medium text-customGray leading-5">
Consulta con Kevin cuales son los nombres de los colores, ese "CustomGray" va a tender a confundir cuando se agreguen mas colores

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +                  <div className="flex mb-12 mt-12  sm:justify-center">
Aqui veo 2 cosas interesantes:
1. Por que usas sm? sm va a hacer que cambie cuando llegue a 640
2. Revisa el formateo de codigo, esta mal formateado

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +                      bgColor="bg-[#128C7E]"
Es una buena solucion, pero no es la mejor. Pensa en que este boton podria volverse muy dinamico y que las propiedades vengan desde una api, en ese caso, tailwind no puede renderizar colores si es una variable dinamica y este boton quedaria inservible

2024-05-13 15:51 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +                <img src="Kodify_ilustration.png" alt="Kodify Ilustration" />
Nextjs tiene su propio componente para manejar imagenes, revisalo en la documentacion

2024-05-13 15:51 UTC, HamiltonG98 commented on packages/components/src/Button/Button.tsx
> +        <a href="" className={`font-bold flex gap-x-2 leading-5 ${defaultTextColor} ${defaultTextHover} group flex justify-center items-center w-[203px] h-[48px] rounded-[10px] ${defaultBgColor} sm:m
Un boton no deberia de tener un ancho y alto fijo, se tiene que adaptar al contenido

2024-05-13 15:51 UTC, HamiltonG98 commented on packages/components/src/Button/Button.tsx
> +        <a href="" className={`font-bold flex gap-x-2 leading-5 ${defaultTextColor} ${defaultTextHover} group flex justify-center items-center w-[203px] h-[48px] rounded-[10px] ${defaultBgColor} sm:m
Revisa tambien lo que te mencione antes lo de las propiedades repetidas

2024-05-13 15:51 UTC, HamiltonG98 commented on packages/components/src/Navbar/Navbar.tsx
> +// import { navItems } from '../../../constants/constants';
Elimina los comentarios

2024-05-13 15:51 UTC, HamiltonG98 commented on packages/tailwind-config/src/globals.css
> +.title {
Por que esto esta en global?

2024-05-13 15:51 UTC, HamiltonG98 commented on packages/tailwind-config/tailwind.config.ts
>        screens: {
Elimina la definicion de las screen, trabaja con las default de tailwind

2024-05-14 01:27 UTC, Jmorales1306 commented on packages/tailwind-config/src/globals.css
> +.title {
Por referencia mas que todo, por cuando se haga mas grande el css poder saber a que pertenece

2024-05-15 01:05 UTC, HamiltonG98 requested changes

2024-05-15 01:05 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +                      bgColor="bg-whatsappBtn"
2 observaciones:
1. Respetar los nombres de los colores: whatsappBtn no es nombre de color
2. Mencione anteriormente que esto no cumple con la regla de dinamismo, y al hacer un sitio administrable esto se va a hacer dificil, mejor repararlo ahorita

2024-05-15 01:05 UTC, HamiltonG98 commented on packages/tailwind-config/src/globals.css
> +  --white-Mob: #FAFAFA;
Para css usar Kebab case siempre: white-mob, no white-Mob

2024-05-15 01:05 UTC, HamiltonG98 commented on packages/tailwind-config/src/globals.css
> +.title {
No deberia esta en global

2024-05-15 01:05 UTC, HamiltonG98 commented on packages/tailwind-config/tailwind.config.ts
> +        'richBlack': 'var(--primary-color)',
Aqui igual usar kebab case

2024-05-15 01:12 UTC, Jmorales1306 commented on apps/web/containers/Hero.tsx
> +/* eslint-disable @next/next/no-img-element */
Era porque usaba la etiqueta <img>, como ahora ocupo el componente de next ya no es necesario

2024-05-15 06:04 UTC, HamiltonG98 requested changes

2024-05-15 06:04 UTC, HamiltonG98 commented on apps/web/containers/Hero.tsx
> +                      bgColor="bg-dark-cyan"
Esto sigue sin ser dinamico

2024-05-15 06:04 UTC, HamiltonG98 commented on packages/components/src/Button/Button.tsx
> +import * as bsIcon from 'react-icons/bs';
Hay que refactorizar el boton para que sea dinamico

2024-05-15 06:04 UTC, HamiltonG98 commented on packages/tailwind-config/src/globals.css
> +  /* Color text */
Por que especificamente es para texto?
Ubicalo debajo del primary normal para que esten en orden

2024-05-15 06:04 UTC, HamiltonG98 commented on packages/tailwind-config/tailwind.config.ts
> +        'bgMobile': 'var(--white-mob)',
Usa kebab case

2024-05-16 03:37 UTC, HamiltonG98 requested changes

2024-05-16 03:37 UTC, HamiltonG98 commented on apps/web/.eslintrc.js
> +  extends: ["@packages/eslint-config/next.js"],P
Hay una P

2024-05-16 03:37 UTC, HamiltonG98 commented on packages/components/src/Button/Button.jsx
> +      <style jsx>{`
Documentar que esta seccion son los estilos personalizados con un comentario

2024-05-16 03:50 UTC, HamiltonG98 approved these changes

2024-05-16 03:50 UTC, merged