Feat/web 26
KodifyDevs/newwebsite.ui pull request #37
Opened 2024-06-07 06:56 UTC by Dierish05

## Description
- este pr trae la seccion del who we are

## Pull request checklist
Please check if your PR fulfills the following requirements:
- [X] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed. (Add screenshot)
- [ ] Is my code avoiding performance problems (ex: rendering issues, amount of queries against the database, n+1 problem, infinite loops, memory usage)
- [ ] Is my code handling integration exceptions (ex: timeout error while calling an external service)
- [ ] My code includes usage metrics (ex: google analytics events, logs)
- [ ] My code includes restriction of access based on roles and permissions

## Pull request type
 
 

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] Feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## JIRA Ticket Link

JIRA Ticket: https://kodifydevs.atlassian.net/browse/WEB-26

## Commands to be executed or config files to be changed
- 

## Other information / Screenshots (Required for UI Changes)

![image](https://github.com/KodifyDevs/newwebsite.ui/assets/85861227/5442a417-b5e8-4279-9cf4-f50dcad80cb4)
![image](https://github.com/KodifyDevs/newwebsite.ui/assets/85861227/70c589cf-a546-4ec2-9762-76ce3f46b4e3)
![image](https://github.com/KodifyDevs/newwebsite.ui/assets/85861227/39a06ef8-6147-4158-b7c2-30a96904a6a7)
![image](https://github.com/KodifyDevs/newwebsite.ui/assets/85861227/06c98e59-597a-47e9-a62c-9de57f8ed136)

2024-06-10 18:20 UTC, HamiltonG98 requested changes
Revisa el linter que estas ocupando, vi algunas cosas cosas que no estaban formateadas y no es codigo legible

2024-06-10 18:20 UTC, HamiltonG98 commented on apps/web/containers/index.js
> +//export {default as Hero} from './src/Hero';
Elimina este comentario

2024-06-10 18:20 UTC, HamiltonG98 commented on apps/web/containers/src/Hero/index.js
> +//export { default } from './Hero';
Por que esta comentado?

2024-06-10 18:20 UTC, HamiltonG98 commented on apps/web/containers/src/HowWeAre/HowWeAre.jsx
> +      {/* hacer supongo un grid o flex para dejar lista la parte de desktop */}
Podes actualizar este comentario ahora que ya esta listo

2024-06-10 18:20 UTC, HamiltonG98 commented on apps/web/containers/src/HowWeAre/HowWeAre.jsx
> +              <div className=" flex w-fit pt-6 lg:pt-0 mb-12 mx-auto lg:my-auto" >
Las clases deben llevar un orden, todas las clases de mobile van primero, despues todo lo de tablet y por ultimo todo lo de desktop. Hay un lg: en medio de las de mobile

2024-06-10 18:20 UTC, HamiltonG98 commented on apps/web/containers/src/HowWeAre/HowWeAre.jsx
> +            <div className=" lg:h-[568px] grid grid-cols-1">
aqui igual, tenes un lg de primero, deberia ir de ultimo

2024-06-14 05:44 UTC, Dierish05 commented on apps/web/containers/src/HowWeAre/HowWeAre.jsx
> +              <div className=" flex w-fit pt-6 lg:pt-0 mb-12 mx-auto lg:my-auto" >
si, eso hacia, en algunos si tuve el error de dejarlos donde no era

2024-06-21 03:12 UTC, HamiltonG98 approved these changes

2024-06-21 03:12 UTC, merged